FROM python:3.5-alpine
COPY . /code
WORKDIR /code
RUN python setup.py install
RUN pip install gunicorn
ARG INTERNAL_ACC_IDNEST_URL
ARG INTERNAL_RECS_API_URL
ARG EXTERNAL_ARCHSTOR_URL
ARG EXTERNAL_QREMIS_API_URL
ARG INTERNAL_QREMIS_API_URL
ARG PORT="8915"
ARG WORKERS="4"
ARG TIMEOUT="30"
ARG SECRET_KEY="supplyThisAtBuildTime"
ARG VERBOSITY="WARN"
ENV \
 DEAD_SIMPLE_INTERFACE_INTERNAL_ACC_IDNEST_URL=$INTERNAL_ACC_IDNEST_URL \
 DEAD_SIMPLE_INTERFACE_INTERNAL_RECS_API_URL=$INTERNAL_RECS_API_URL \
 DEAD_SIMPLE_INTERFACE_EXTERNAL_ARCHSTOR_URL=$EXTERNAL_ARCHSTOR_URL \
 DEAD_SIMPLE_INTERFACE_EXTERNAL_QREMIS_API_URL=$EXTERNAL_QREMIS_API_URL \
 DEAD_SIMPLE_INTERFACE_INTERNAL_QREMIS_API_URL=$INTERNAL_QREMIS_API_URL \
 DEAD_SIMPLE_INTERFACE_VERBOSITY=$VERBOSITY \
 DEAD_SIMPLE_INTERFACE_SECRET_KEY=$SECRET_KEY \
 WORKERS=$WORKERS \
 TIMEOUT=$TIMEOUT \
 PORT=$PORT
CMD gunicorn dead_simple_interface:app -w ${WORKERS} -t ${TIMEOUT} -b 0.0.0.0:${PORT}
